name = "fastapi"
compatibility_date = "2022-04-05"

[vars]
UPSTASH_REDIS_REST_URL = "https://relevant-grouse-51524.upstash.io"
UPSTASH_REDIS_REST_TOKEN = "AclEAAIncDExZTEyZGIyNTQ1YjA0YzNjODc5MjczMDUxM2M5OGU5MXAxNTE1MjQ"
